sudo: false
language: rust

rust:
  - nightly
notifications:
  email:
    - s.pepyakin@gmail.com
before_script:
  - rustc --version
  - cargo --version
script:
  - CC=clang CXX=clang++ cargo test --all --verbose
